apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-nfs-pv
spec:
  capacity:
    storage: 1000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fss.csi.oraclecloud.com
    # Format: <FILE_SYSTEM_OCID>:<MOUNT_TARGET_PRIVATE_IP:PATH>
    volumeHandle: <REPLACE_WITH_YOUR_VOLUME_HANDLE>
