apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""       # <— force match with static PV  
  resources:
    requests:
      storage: 200Gi
  volumeName: jellyfin-media-pv
