apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""       # <— force match with static PV
  resources:
    requests:
      storage: 20Gi
  volumeName: jellyfin-config-pv
